import type { SiteContent } from '@/types/content';

export const defaultContent: SiteContent = {
  colors: {
    crimson: '#A63028',
    crimsonDk: '#7A1E14',
    rose: '#C4816A',
    roseLt: '#D9A896',
    cream: '#F5EDE3',
    creamDk: '#EAD9C8',
    warmBg: '#FAF5F0',
    dark: '#1C0A06',
    mid: '#5A3328',
    radius: '12px',
  },
  nav: {
    ctaText: 'Acessar o curso',
    ctaLink: 'https://pay.kiwify.com.br/Abzsnsi',
  },
  hero: {
    tag: 'Método ReCore · Tatiéli Araújo',
    titleBefore: 'Seu core tem\nmemória.',
    titleEm: 'Ajude-o a lembrar',
    titleAfter: 'quem ele era.',
    subtitle:
      'Recuperação de diástase e disfunção abdominal para quem sente que o abdômen não é mais o mesmo, independente do motivo.',
    ctaText: 'Começar Minha Recuperação',
    ctaLink: 'https://pay.kiwify.com.br/Abzsnsi',
    note: 'Garantia de 7 dias',
    imageSrc: '/hero/model.jpg',
    proof: [
      { num: '17', label: 'Anos de\nexperiência' },
      { num: '100%', label: 'Online' },
      { num: '+30', label: 'Abdômens\nrecuperados' },
    ],
  },
  bio: {
    tag: 'Quem vai te guiar',
    heading: 'Eu sou Tatiéli Araújo',
    paragraphs: [
      'Com mais de 17 anos de profissão, especializada em recuperação funcional abdominal e corporal. Ao longo da carreira, acompanhei pessoas que chegaram com queixas que pareciam estéticas mas tinham origem muscular e postural.',
      'Desenvolvi o Método ReCore a partir dessa experiência prática: um protocolo que trata a causa da disfunção abdominal, não só a aparência. Seja no pós-parto, na diástase instalada há anos, na hérnia umbilical ou no abdômen que estufa sem explicação aparente, o caminho é o mesmo: reconstruir o core de dentro para fora.',
      'Vou te guiar nesse processo com exercícios progressivos, explicações claras e uma abordagem que respeita o tempo e o corpo de cada pessoa.',
    ],
    quote:
      'A maioria das pessoas aprende a conviver com um corpo que não funciona direito. Eu acredito que dá pra mudar isso.',
    quoteAuthor: 'Tatiéli Araújo',
  },
  problema: {
    tag: 'Você se reconhece?',
    heading: 'O abdômen mudou.\nExiste causa e tratamento.',
    lead: 'Diástase, barriguinha que resiste à dieta e ao treino, abdômen que estufa ao longo do dia. Esses sinais têm origem fisiológica e o Método ReCore trata cada um deles.',
    cards: [
      { title: 'Pós-parto', body: 'A gestação separa os músculos abdominais e o core perde função e forma. O retorno espontâneo é raro.' },
      { title: 'Abdômen em U', body: 'A barriguinha baixa aparece mesmo em quem tem peso saudável. O problema está na musculatura, não no peso.' },
      { title: 'Abdômen estufado', body: 'O inchaço que piora ao longo do dia costuma estar ligado à falta de tônus abdominal, não à alimentação.' },
      { title: 'Falsa magra', body: 'Corpo enxuto mas com a pochete que não sai. Exercício convencional não resolve porque não alcança a camada certa.' },
      { title: 'Diástase abdominal', body: 'A separação da linha alba causa protrusão, dor lombar e disfunção do core. Precisa de protocolo específico para fechar.' },
    ],
  },
  metodo: {
    tag: 'O Método',
    heading: 'O protocolo trabalha onde o treino convencional não chega.',
    paragraphs: [
      'Musculatura profunda, assoalho pélvico, postura e linha alba. O Método ReCore foi desenvolvido por Tatiéli Araújo para tratar a causa da disfunção, não só o que aparece por fora.',
      'Cada fase do protocolo tem justificativa fisiológica. A ordem dos exercícios importa. O que vem antes prepara o que vem depois.',
    ],
    beforeImageSrc: '/pacientes/paciente-4-antes.JPG',
    afterImageSrc: '/pacientes/paciente-4-depois.JPG',
    pillars: [
      { title: 'Musculatura profunda', body: 'Ativa transverso abdominal antes de qualquer exercício de superfície.' },
      { title: 'Fechamento da diástase', body: 'Protocolo progressivo que fecha a linha alba com segurança e sequência certa.' },
      { title: 'Postura e função', body: 'Corrige os desvios posturais que a gestação instala no corpo.' },
      { title: 'Assoalho pélvico', body: 'Integra a recuperação pélvica à reconstrução do core desde o início.' },
    ],
  },
  videos: {
    tag: 'Resultados reais',
    heading: 'Diástase antes e depois do protocolo',
    lead: 'Paciente real de Tatiéli Araújo. A disfunção abdominal visível antes do método e o core recuperado depois.',
  },
  carousel: {
    tag: 'Galeria',
    heading: 'Pacientes reais, resultados reais.',
    lead: 'Fotos antes e depois de mulheres que fizeram o Método ReCore com acompanhamento de Tatiéli Araújo.',
    images: [
      { src: '/pacientes/paciente-1-antes-frente.JPG', label: 'Paciente 1', type: 'antes' },
      { src: '/pacientes/paciente-1-antes-lado.JPG',   label: 'Paciente 1', type: 'antes' },
      { src: '/pacientes/paciente-1-depois-lado.jpg',  label: 'Paciente 1', type: 'depois' },
      { src: '/pacientes/paciente-2-depois-frente.jpg',label: 'Paciente 2', type: 'depois' },
      { src: '/pacientes/paciente-4-antes.JPG',        label: 'Paciente 4', type: 'antes' },
      { src: '/pacientes/paciente-4-depois.JPG',       label: 'Paciente 4', type: 'depois' },
      { src: '/pacientes/profundidade-diastase-antes.JPG',  label: 'Diástase', type: 'antes' },
      { src: '/pacientes/profundidade-diastase-depois.JPG', label: 'Diástase', type: 'depois' },
    ],
  },
  paraQuem: {
    tag: 'Para quem é',
    heading: 'Diástase não tem perfil. Qualquer pessoa pode ter.',
    lead: 'O protocolo foi desenvolvido para quem tem abdômen disfuncional, independente do motivo ou de quando o problema começou.',
    items: [
      'Você teve filho e o abdômen ficou diferente desde então.',
      'A barriguinha baixa não some com exercício nem com dieta.',
      'Você tem diagnóstico de diástase abdominal.',
      'O abdômen estufa muito ao longo do dia.',
      'Você sente dor lombar sem causa aparente.',
      'Quer se exercitar mas tem receio de agravar a diástase.',
      'O core está sem força e você sente isso no dia a dia.',
      'Perdeu muito peso e o abdômen ficou fraco e sem tônus.',
    ],
  },
  hernia: {
    tag: 'Além do abdômen',
    heading: 'Core fraco e dor cervical têm mais relação do que parece',
    paragraphs: [
      'A coluna vertebral funciona como uma cadeia cinética: o que acontece em uma região afeta as outras. Quando a musculatura do core está fraca ou disfuncional, o corpo compensa redistribuindo a carga para outras estruturas, incluindo a região lombar, dorsal e cervical.',
      'Pesquisas recentes mostram que mulheres com dor cervical crônica apresentam função reduzida do transverso abdominal, o músculo profundo que é o principal alvo do Método ReCore. Isso indica que a disfunção do core pode contribuir para compensações posturais que sobrecarregam os músculos do pescoço e do trapézio, aumentando a pressão sobre os discos cervicais.',
      'Fortalecer o core de forma adequada ajuda a corrigir a postura global, reduzir as tensões compensatórias no trapézio e nos músculos cervicais e diminuir a sobrecarga sobre a região do pescoço. Não substitui o tratamento médico da hérnia cervical, mas atua como suporte importante para quem convive com esse diagnóstico.',
    ],
    cards: [
      { title: 'Core fraco', body: 'Reduz a estabilidade da coluna inteira, forçando músculos cervicais a compensar.' },
      { title: 'Postura anterior', body: 'Cabeça projetada à frente aumenta a carga sobre os discos cervicais em até 4x.' },
      { title: 'Trapézio sobrecarregado', body: 'Tensão crônica no trapézio superior é sintoma de instabilidade postural do tronco.' },
      { title: 'Core forte', body: 'Estabiliza o tronco, libera a tensão cervical e melhora o alinhamento de toda a coluna.' },
    ],
  },
  herniaUmbilical: {
    tag: 'Hérnia umbilical',
    heading: 'Hérnia umbilical e diástase costumam andar juntas.',
    paragraphs: [
      'Quando a musculatura do core está fraca, a pressão intra-abdominal aumenta. Esse aumento de pressão pode empurrar tecido pelo umbigo, favorecendo a hérnia. Quem já tem o diagnóstico frequentemente também tem diástase abdominal sem saber.',
      'O Método ReCore trabalha a ativação da musculatura profunda, reduzindo essa pressão excessiva e melhorando a função abdominal. Não substitui avaliação médica, mas atua diretamente na causa mecânica do problema: core fraco não sustenta.',
    ],
    caption: 'Paciente com hérnia umbilical e diástase abdominal acompanhada pelo Método ReCore.',
    image1Src: '/pacientes/paciente5-frente.JPG',
    image2Src: '/pacientes/paciente5-lateral.JPG',
  },
  homens: {
    tag: 'Para homens também',
    heading: 'Diástase e disfunção do core não são exclusividade feminina.',
    paragraphs: [
      'Homens também desenvolvem fraqueza da parede abdominal, especialmente após grande perda de peso, cirurgias ou sedentarismo prolongado. O resultado é parecido: instabilidade, dor lombar, alterações posturais e dificuldade com atividade física.',
      'O Método ReCore trata a raiz do problema. Ativação do transverso, reabilitação do core profundo, progressão de carga. O protocolo se adapta ao corpo, não ao gênero.',
    ],
    cards: [
      { title: 'Grande perda de peso', body: 'Enfraquece a parede abdominal e deixa o core sem sustentação para as atividades do dia a dia.' },
      { title: 'Dor lombar crônica', body: 'Core fraco redistribui carga para a lombar. Tratar o abdômen resolve onde o analgésico não chega.' },
      { title: 'Pós-cirúrgico', body: 'Cirurgias abdominais comprometem a musculatura profunda. Reabilitar o core é parte da recuperação completa.' },
    ],
    imageSrc: '/pacientes/paciente-homem.JPG',
  },
  incluso: {
    tag: 'O que está incluso',
    heading: 'O que você acessa ao entrar',
    items: [
      { title: 'Protocolo completo em vídeo-aulas', body: 'Cada exercício gravado com instrução clara de execução, respiração e posicionamento.' },
      { title: 'Protocolo progressivo estruturado', body: 'Cronograma semana a semana para que cada fase do core seja trabalhada na sequência certa.' },
      { title: 'Guia de avaliação da diástase', body: 'Como identificar o grau da sua diástase e adaptar os exercícios com segurança.' },
      { title: 'Acesso por 6 meses', body: 'Assista quando e onde quiser por 6 meses. Reveja quantas vezes precisar.' },
      { title: 'Atualizações inclusas', body: 'Novos conteúdos adicionados sem custo extra durante o período de acesso.' },
      { title: 'Garantia de 7 dias', body: 'Se não for o que você esperava, devolvemos o dinheiro. Sem formulário, sem prazo de resposta.' },
    ],
  },
  oferta: {
    tag: 'Planos',
    heading: 'Escolha o plano ideal para você',
    lead: 'Acesso imediato após confirmação. Garantia de 7 dias.',
    planos: [
      {
        name: 'Completo',
        badgeColor: 'blue',
        price: '267',
        period: 'Acesso por 6 meses',
        featured: true,
        featuredLabel: 'Mais escolhido',
        items: [
          'Acesso completo ao curso',
          'Assista no seu ritmo, onde e quando quiser',
          'Atualizações com novos vídeos e conteúdos',
          'Novos exercícios de mobilidade e fortalecimento',
          'Conteúdo para diástase abdominal e disfunções musculares',
          'Grupo exclusivo para tirar dúvidas com a profissional',
        ],
        ctaText: 'Começar com Completo',
        ctaLink: 'https://pay.kiwify.com.br/Abzsnsi',
        footnote: '',
      },
      {
        name: 'Mentoria ReCore',
        badgeColor: 'gold',
        price: '597',
        period: 'Acompanhamento individual',
        featured: false,
        featuredLabel: '',
        items: [
          'Tudo do plano Completo, mais:',
          'Mentoria online por videochamada',
          'Dois encontros por semana',
          'Avaliação postural e de diástase individual',
          'Plano de exercícios personalizado',
          'Correção da execução em tempo real',
          'Acompanhamento da evolução com ajustes contínuos',
        ],
        ctaText: 'Quero a Mentoria',
        ctaLink: 'https://pay.kiwify.com.br/dIbLMgP',
        footnote: 'Acompanhamento próximo para executar os exercícios com mais segurança e constância.',
      },
    ],
    note: 'Pagamento seguro via Kiwify · Acesso imediato após confirmação',
  },
  garantia: {
    tag: 'Risco zero',
    days: '7',
    heading: 'Experimente sem compromisso',
    body: 'Se em até 7 dias o método não for o que você esperava, basta pedir o reembolso. Devolvemos 100% do valor. Sem questionamentos, sem burocracia. Você não tem nada a perder além da diástase.',
  },
  footer: {
    copyright: '2026 Método ReCore por Tatiéli Araújo',
    whatsapp: 'https://wa.me/5567992128879',
    whatsappDisplay: '+55 67 99212-8879 (WhatsApp)',
    instagram: 'https://instagram.com/tatieliaraujo_',
    instagramHandle: '@tatieliaraujo_',
    tiktok: 'https://tiktok.com/@esteticatatieli',
    tiktokHandle: '@esteticatatieli',
  },
  affiliates: [
    { username: 'elisa.almeidah', link: 'https://pay.kiwify.com.br/Abzsnsi?afid=9GCtTSYG' },
  ],
};
